name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: jetify-com/devbox-install-action@22b0f5500b14df4ea357ce673fbd4ced940ed6a1 # v0.13.0
        with:
          enable-cache: "true"
      # The registry-url must be set for authentication to work on the npm publish step
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
      - run: devbox run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}